import Link from "next/link";
import { auth } from "@/auth";
import { ListingDiagnosisForm } from "@/components/analysis/listing-diagnosis-form";
import { db } from "@/server/db";

const labels: Record<string, string> = { "product-lookup": "商品事实查询", "review-insights": "评论洞察", "keyword-research": "关键词研究", "listing-diagnosis": "Listing 诊断" };

export default async function ProjectAnalysisPage({ params }: { params: { projectId: string } }) {
  const session = await auth(); if (!session?.user?.id) return null;
  const project = await db.project.findFirst({ where: { id: params.projectId, userId: session.user.id }, select: { id: true, name: true, trackedAsins: { orderBy: { asin: "asc" }, select: { id: true, asin: true, title: true } }, analysisRuns: { orderBy: { requestedAt: "desc" }, take: 50, select: { id: true, toolKey: true, status: true, requestedAt: true, sourceAsOf: true, errorMessage: true } } } });
  if (!project) return null;
  return <div className="mx-auto max-w-6xl space-y-8"><div className="flex items-end justify-between gap-4"><div><p className="font-label text-xs uppercase tracking-[0.2em] text-[var(--md-primary)]">Analysis</p><h1 className="mt-3 font-headline text-3xl font-bold text-[var(--md-on-surface)]">分析记录</h1><p className="mt-2 font-label text-sm text-[var(--md-on-surface-variant)]">{project.name} 的已保存分析与本地 Listing 诊断。</p></div><Link href="/tools" className="rounded-lg border border-[var(--md-outline-variant)] px-4 py-2 font-label text-sm">打开工具箱</Link></div>{project.trackedAsins.length ? <section><h2 className="mb-3 font-headline text-lg font-semibold">Listing 健康诊断</h2><p className="mb-3 font-label text-sm text-[var(--md-on-surface-variant)]">只读取最新商品快照和关键词观察，不请求外部 Provider。</p><ListingDiagnosisForm projectId={project.id} asins={project.trackedAsins} /></section> : null}{project.analysisRuns.length ? <div className="space-y-3">{project.analysisRuns.map(run => <Link key={run.id} href={`/analysis/${run.id}`} className="block rounded-xl border border-[var(--md-outline-variant)] bg-[var(--md-surface-container)] p-5 transition hover:border-[var(--md-primary)]"><div className="flex items-start justify-between gap-4"><div><h2 className="font-headline text-lg font-semibold">{labels[run.toolKey] ?? run.toolKey}</h2><p className="mt-1 font-label text-sm text-[var(--md-on-surface-variant)]">{run.requestedAt.toLocaleString("zh-CN")} · 数据截止 {run.sourceAsOf?.toLocaleString("zh-CN") ?? "未知"}</p>{run.errorMessage ? <p className="mt-2 font-label text-sm text-[var(--md-error)]">{run.errorMessage}</p> : null}</div><span className="font-label text-sm text-[var(--md-on-surface-variant)]">{run.status}</span></div></Link>)}</div> : <div className="rounded-xl border border-dashed border-[var(--md-outline-variant)] p-8 text-center font-label text-sm text-[var(--md-on-surface-variant)]">尚无分析记录。</div>}</div>;
}
