import Link from "next/link";
import { AnalysisRunActions } from "@/components/analysis/analysis-run-actions";

function statusLabel(status: string) { return status === "SUCCESS" ? "已完成" : status === "FAILED" ? "失败" : status === "RUNNING" ? "运行中" : "等待中"; }
function value(value: unknown) { return value === null || value === undefined || value === "" ? "—" : String(value); }

export function AnalysisRunDetail({ run, projects, hideResult = false }: { run: { id: string; toolKey: string; analysisType: string; marketplace: string; status: string; requestedAt: Date; sourceAsOf: Date | null; provider: string | null; errorCode: string | null; errorMessage: string | null; attemptCount: number; projectId: string | null; resultJson: unknown }; projects: Array<{ id: string; name: string; marketplace: string }>; hideResult?: boolean }) {
  const result = run.resultJson && typeof run.resultJson === "object" && !Array.isArray(run.resultJson) ? run.resultJson as Record<string, unknown> : null;
  return <div className="mx-auto max-w-4xl space-y-6"><div className="flex items-start justify-between gap-4"><div><p className="font-label text-xs uppercase tracking-[0.2em] text-[var(--md-primary)]">Analysis run</p><h1 className="mt-3 font-headline text-3xl font-bold text-[var(--md-on-surface)]">商品事实查询</h1><p className="mt-2 font-label text-sm text-[var(--md-on-surface-variant)]">{run.marketplace} · 请求于 {run.requestedAt.toLocaleString("zh-CN")}</p></div><span className={`rounded-full px-3 py-1 font-label text-sm ${run.status === "SUCCESS" ? "bg-emerald-500/15 text-emerald-400" : run.status === "FAILED" ? "bg-[var(--md-error)]/15 text-[var(--md-error)]" : "bg-amber-500/15 text-amber-300"}`}>{statusLabel(run.status)}</span></div><AnalysisRunActions runId={run.id} status={run.status} marketplace={run.marketplace} projects={projects} attachedProjectId={run.projectId} />{run.projectId ? <p className="font-label text-sm text-[var(--md-on-surface-variant)]">已关联到项目。<Link href={`/projects/${run.projectId}/analysis`} className="text-[var(--md-primary)]">查看项目分析记录</Link></p> : null}{run.status === "FAILED" ? <div className="rounded-xl border border-[var(--md-error)]/30 bg-[var(--md-error)]/10 p-5"><h2 className="font-headline text-lg font-semibold text-[var(--md-error)]">运行失败</h2><p className="mt-2 font-label text-sm text-[var(--md-on-surface)]">{run.errorMessage ?? "未返回具体错误"}</p><p className="mt-1 font-mono text-xs text-[var(--md-on-surface-variant)]">{run.errorCode ?? "UNKNOWN"} · 第 {run.attemptCount} 次尝试</p></div> : null}{result && !hideResult ? <section className="rounded-2xl border border-[var(--md-outline-variant)] bg-[var(--md-surface-container)] p-6"><h2 className="font-headline text-xl font-semibold text-[var(--md-on-surface)]">查询结果</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2">{[["ASIN", result.asin], ["标题", result.title], ["品牌", result.brand], ["价格", result.price], ["评分", result.rating], ["评论数", result.reviewCount], ["BSR", result.bsr], ["分类", result.category]].map(([label, item]) => <div key={String(label)}><dt className="font-label text-xs text-[var(--md-on-surface-variant)]">{String(label)}</dt><dd className="mt-1 font-label text-sm text-[var(--md-on-surface)]">{value(item)}</dd></div>)}</dl><div className="mt-6 rounded-lg border border-[var(--md-outline-variant)] bg-[var(--md-surface)] p-4 font-label text-sm text-[var(--md-on-surface-variant)]"><p>来源：{value(result.sourceKind)} · {run.provider ?? "未记录 Provider"}</p><p className="mt-1">数据截止：{run.sourceAsOf?.toLocaleString("zh-CN") ?? "未知"}</p><p className="mt-1">限制：{value(result.limitation)}</p></div></section> : null}</div>;
}
