import { auth } from "@/auth";
import { Surface } from "@/components/projects/project-workspace-shell";
import { DataProvenance } from "@/components/projects/data-provenance";
import { db } from "@/server/db";

export default async function ProjectReviewsPage({ params }: { params: { projectId: string } }) {
  const session = await auth();
  if (!session?.user?.id) return null;
  const project = await db.project.findFirst({ where: { id: params.projectId, userId: session.user.id }, select: { id: true, trackedAsins: { where: { role: "OWN" }, select: { id: true, asin: true } } } });
  if (!project) return null;
  const reviews = await db.productReview.findMany({ where: { trackedAsin: { projectId: project.id, role: "OWN" } }, include: { trackedAsin: { select: { asin: true } }, capture: { select: { sourceKind: true, provider: true, apiName: true, capturedAt: true } } }, orderBy: [{ reviewDate: "desc" }, { firstSeenAt: "desc" }], take: 100 });
  return <div className="mx-auto max-w-6xl space-y-8"><div><p className="font-label text-xs uppercase tracking-[0.2em] text-[var(--md-primary)]">Review monitoring</p><h1 className="font-headline mt-3 text-3xl font-bold tracking-tight text-[var(--md-on-surface)]">评论监控</h1><p className="mt-2 max-w-3xl font-label text-sm text-[var(--md-on-surface-variant)]">仅监控自有 ASIN，展示已采集的全部评论；新增评论会进入项目概览和日报，其中 1–3 星会重点标记。</p></div><Surface><div className="flex items-end justify-between gap-4"><div><h2 className="font-headline text-xl font-semibold text-[var(--md-on-surface)]">全部评论</h2><p className="mt-1 font-label text-sm text-[var(--md-on-surface-variant)]">最近 100 条</p></div><span className="font-label text-sm text-[var(--md-on-surface-variant)]">{reviews.length} 条</span></div>{reviews.length ? <div className="mt-5 space-y-3">{reviews.map((review) => <article key={review.id} className="rounded-xl border border-[var(--md-outline-variant)] bg-[var(--md-surface-container-lowest)] p-5"><div className="flex items-start justify-between gap-4"><div><p className="font-label text-xs text-[var(--md-on-surface-variant)]">{review.trackedAsin.asin} · {review.reviewDate ? review.reviewDate.toLocaleDateString("zh-CN") : "日期未知"}</p><h3 className="mt-1 font-headline text-base font-semibold text-[var(--md-on-surface)]">{review.title ?? "未提供标题"}</h3></div><span className={`rounded-full px-3 py-1 font-label text-xs ${review.rating === 1 ? "bg-[var(--md-error)]/15 text-[var(--md-error)]" : review.rating <= 3 ? "bg-amber-500/15 text-amber-300" : "bg-emerald-500/15 text-emerald-300"}`}>{review.rating} 星</span></div><p className="mt-3 whitespace-pre-wrap font-label text-sm leading-6 text-[var(--md-on-surface-variant)]">{review.content ?? "未提供评论正文"}</p><DataProvenance capture={review.capture} fallbackCapturedAt={review.firstSeenAt} /></article>)}</div> : <div className="mt-5 rounded-xl border border-dashed border-[var(--md-outline-variant)] p-8 text-center font-label text-sm text-[var(--md-on-surface-variant)]">暂无已采集评论。配置评论数据源后会显示在这里。</div>}</Surface></div>;
}
