import Link from "next/link";

import { DataProvenance } from "@/components/projects/data-provenance";

type Snapshot = { capturedAt: Date; price: { toString(): string } | null; coupon: number | null; dealType: string | null; rating: { toString(): string } | null; bsr: number | null; category: string | null; categoryNodeId: string | null; bsrCategory: unknown; sellerCount: number | null; buyboxSeller: string | null; buyboxSellerId: string | null; photoUrls: unknown; ebcPhotoUrls: unknown; variantCount: number | null; capture: { sourceKind: "LIVE_PROVIDER" | "MOCK" | "IMPORT" | "USER_INPUT" | "DERIVED" | "LEGACY_UNKNOWN"; provider: string; apiName: string; capturedAt: Date | null } | null };

function amount(value: Snapshot["price"] | null) { return value === null ? "-" : `$${Number(value.toString()).toFixed(2)}`; }
function change(current: number | null, previous: number | null, unit = "") { if (current === null || Number.isNaN(current)) return "数据缺失"; if (previous === null || Number.isNaN(previous)) return `当前 ${current}${unit}`; if (current === previous) return "无变化"; return `${previous}${unit} → ${current}${unit}`; }
function changed(current: unknown, previous: unknown) { return previous !== null && previous !== undefined && JSON.stringify(current) !== JSON.stringify(previous); }
function categoryLabel(snapshot: Snapshot) { return snapshot.category || "数据缺失"; }
function subcategoryLabel(value: unknown) { if (!Array.isArray(value) || !value.length) return "数据缺失"; const rows = value.flatMap((item) => { if (!Array.isArray(item) || typeof item[0] !== "string") return []; const rank = typeof item[2] === "string" || typeof item[2] === "number" ? item[2] : null; return [`${item[0]}${rank !== null ? ` · #${rank}` : ""}`]; }); return rows.length ? [...new Set(rows)].join("\n") : "数据缺失"; }
function buyboxChange(current: string | null, previous: string | null) { const currentLabel = current?.trim() || "未识别"; if (previous === undefined || previous === null) return `当前 ${currentLabel}`; const previousLabel = previous.trim() || "未识别"; return currentLabel === previousLabel ? "无变化" : `${previousLabel} → ${currentLabel}`; }
function sellerStatus(current: number | null, previous: number | null) { if (current === null) return "数据缺失"; const describe = (count: number) => count <= 0 ? "无可售卖家" : count === 1 ? "无跟卖（1 名卖家）" : `有跟卖（${count} 名卖家）`; if (previous === null || previous === undefined) return `当前 ${describe(current)}`; return current === previous ? `${describe(current)}，无变化` : `${describe(previous)} → ${describe(current)}`; }

export function ListingIntelligenceCard({ item, projectId }: { item: { id: string; asin: string; role: "OWN" | "COMPETITOR"; title: string | null; consecutiveFailures: number; snapshots: Snapshot[] }; projectId: string }) {
  const [latest, previous] = item.snapshots;
  const own = item.role === "OWN";
  const signals = [{ label: "价格", value: latest ? `${amount(previous?.price ?? null)} → ${amount(latest.price)}` : "-" }, { label: "Coupon / 秒杀", value: !latest ? "-" : `${previous?.coupon ?? 0}/${previous?.dealType ?? "无"} → ${latest.coupon ?? 0}/${latest.dealType ?? "无"}` }, { label: "变体", value: latest ? change(latest.variantCount, previous?.variantCount ?? null, " 个") : "-" }, { label: "评分", value: latest ? change(Number(latest.rating?.toString() ?? NaN), previous ? Number(previous.rating?.toString() ?? NaN) : null) : "-" }, { label: "大类 Rank", value: latest ? change(latest.bsr, previous?.bsr ?? null) : "-" }, { label: "主图", value: latest && changed(latest.photoUrls, previous?.photoUrls) ? "较上次已更换" : "未发现变化" }, { label: "A+ 图片", value: latest && changed(latest.ebcPhotoUrls, previous?.ebcPhotoUrls) ? "较上次已更换" : "未发现变化" }];
  if (latest && own) signals.splice(5, 0, { label: "Buy Box 卖家", value: buyboxChange(latest.buyboxSeller, previous?.buyboxSeller ?? null) }, { label: "卖家数量 / 跟卖", value: sellerStatus(latest.sellerCount, previous?.sellerCount ?? null) });
  return <article className="rounded-xl border-t-2 border-[var(--md-outline)] bg-[#11100d] p-5 font-mono text-[#e7e1d6] transition hover:border-[var(--md-primary)]"><div className="flex items-start justify-between gap-4 border-b border-[#5d584e] pb-4"><div><div className="flex items-center gap-2"><span className={`rounded-sm px-2 py-1 text-[10px] font-semibold ${own ? "bg-[var(--md-primary)]/15 text-[var(--md-primary)]" : "bg-sky-500/15 text-sky-300"}`}>{own ? "自有 Listing" : "竞品"}</span><span className="text-xs text-[#b8b1a4]">{item.asin}</span></div><h2 className="mt-3 line-clamp-2 text-sm font-semibold">{item.title ?? "等待首次 Listing 数据"}</h2></div><Link href={`/projects/${projectId}/asins/${item.id}`} className="shrink-0 text-sm text-[var(--md-primary)]">详情</Link></div><p className="mt-3 text-xs text-[#b8b1a4]">{item.consecutiveFailures ? `最近采集失败 ${item.consecutiveFailures} 次` : `最近采集：${latest ? latest.capturedAt.toLocaleString("zh-CN") : "无"}`}</p>{latest ? <DataProvenance capture={latest.capture} fallbackCapturedAt={latest.capturedAt} /> : null}{latest ? <dl className="mt-5 grid gap-x-5 gap-y-4 sm:grid-cols-2"><div><dt className="text-xs text-[#b8b1a4]">所属大类</dt><dd className="mt-1 text-sm leading-5">{categoryLabel(latest)}</dd></div><div><dt className="text-xs text-[#b8b1a4]">所属细分类目</dt><dd className="mt-1 whitespace-pre-line text-sm leading-5">{subcategoryLabel(latest.bsrCategory)}</dd></div>{signals.map((signal) => <div key={signal.label}><dt className="text-xs text-[#b8b1a4]">{signal.label}</dt><dd className="mt-1 text-sm leading-5">{signal.value}</dd></div>)}</dl> : null}</article>;
}
